GET http://localhost:3333/

###

GET http://localhost:3333/user/2

###

GET http://localhost:3333/users

###

POST http://localhost:3333/user
content-type: application/json

{
  "name": "Luiz Seixas",
  "email": "luiz2@mail.com",
  "password": "1234",
  "passwordConfirmation": "1234"
}
